# Parsed from https://www.ibm.com/docs/en/spectrum-lsf/10.1.0?topic=options-o
bjobs_fields = [
    {"name": "jobid", "width": 7, "aliases": "id", "unit": None},
    {"name": "jobindex", "width": 8, "aliases": None, "unit": None},
    {"name": "stat", "width": 5, "aliases": None, "unit": None},
    {"name": "user", "width": 7, "aliases": None, "unit": None},
    {"name": "user_group", "width": 15, "aliases": "ugroup", "unit": None},
    {"name": "queue", "width": 10, "aliases": None, "unit": None},
    {"name": "job_name", "width": 10, "aliases": "name", "unit": None},
    {"name": "job_description", "width": 17, "aliases": "description", "unit": None},
    {"name": "proj_name", "width": 11, "aliases": "proj, project", "unit": None},
    {"name": "application", "width": 13, "aliases": "app", "unit": None},
    {"name": "service_class", "width": 13, "aliases": "sla", "unit": None},
    {"name": "job_group", "width": 10, "aliases": "group", "unit": None},
    {"name": "job_priority", "width": 12, "aliases": "priority", "unit": None},
    {"name": "rsvid", "width": 40, "aliases": None, "unit": None},
    {"name": "esub", "width": 20, "aliases": None, "unit": None},
    {"name": "kill_reason", "width": 50, "aliases": None, "unit": None},
    {"name": "suspend_reason", "width": 50, "aliases": None, "unit": None},
    {"name": "resume_reason", "width": 50, "aliases": None, "unit": None},
    {"name": "kill_issue_host", "width": 50, "aliases": None, "unit": None},
    {"name": "suspend_issue_host", "width": 50, "aliases": None, "unit": None},
    {"name": "resume_issue_host", "width": 50, "aliases": None, "unit": None},
    {"name": "dependency", "width": 15, "aliases": None, "unit": None},
    {"name": "pend_reason", "width": 11, "aliases": None, "unit": None},
    {"name": "charged_saap", "width": 50, "aliases": "saap", "unit": None},
    {"name": "command", "width": 15, "aliases": "cmd", "unit": None},
    {"name": "pre_exec_command", "width": 16, "aliases": "pre_cmd", "unit": None},
    {"name": "post_exec_command", "width": 17, "aliases": "post_cmd", "unit": None},
    {
        "name": "resize_notification_command",
        "width": 27,
        "aliases": "resize_cmd",
        "unit": None,
    },
    {"name": "pids", "width": 20, "aliases": None, "unit": None},
    {"name": "exit_code", "width": 10, "aliases": None, "unit": None},
    {"name": "exit_reason", "width": 50, "aliases": None, "unit": None},
    {"name": "interactive", "width": 11, "aliases": None, "unit": None},
    {"name": "from_host", "width": 11, "aliases": None, "unit": None},
    {"name": "first_host", "width": 11, "aliases": None, "unit": None},
    {"name": "exec_host", "width": 11, "aliases": None, "unit": None},
    {"name": "nexec_host", "width": 10, "aliases": None, "unit": None},
    {"name": "ask_hosts", "width": 30, "aliases": None, "unit": None},
    {"name": "alloc_slot", "width": 20, "aliases": None, "unit": None},
    {"name": "nalloc_slot", "width": 10, "aliases": None, "unit": None},
    {"name": "host_file", "width": 10, "aliases": None, "unit": None},
    {"name": "exclusive", "width": 13, "aliases": None, "unit": None},
    {"name": "nreq_slot", "width": 10, "aliases": None, "unit": None},
    {"name": "submit_time", "width": 15, "aliases": None, "unit": "time stamp"},
    {"name": "start_time", "width": 15, "aliases": None, "unit": "time stamp"},
    {
        "name": "estimated_start_time",
        "width": 20,
        "aliases": "estart_time",
        "unit": "time stamp",
    },
    {
        "name": "specified_start_time",
        "width": 20,
        "aliases": "sstart_time",
        "unit": "time stamp",
    },
    {
        "name": "specified_terminate_time",
        "width": 24,
        "aliases": "sterminate_time",
        "unit": "time stamp",
    },
    {"name": "time_left", "width": 11, "aliases": None, "unit": "seconds"},
    {"name": "finish_time", "width": 16, "aliases": None, "unit": "time stamp"},
    {"name": "estimated_run_time", "width": 20, "aliases": "ertime", "unit": "seconds"},
    {"name": "ru_utime", "width": 12, "aliases": None, "unit": "seconds"},
    {"name": "ru_stime", "width": 12, "aliases": None, "unit": "seconds"},
    {"name": "%complete", "width": 11, "aliases": None, "unit": None},
    {"name": "warning_action", "width": 15, "aliases": "warn_act", "unit": None},
    {"name": "action_warning_time", "width": 19, "aliases": "warn_time", "unit": None},
    {"name": "pendstate", "width": 9, "aliases": None, "unit": None},
    {"name": "pend_time", "width": 12, "aliases": None, "unit": "seconds"},
    {"name": "ependtime", "width": 12, "aliases": None, "unit": "seconds"},
    {"name": "ipendtime", "width": 12, "aliases": None, "unit": "seconds"},
    {
        "name": "estimated_sim_start_time",
        "width": 24,
        "aliases": "esstart_time",
        "unit": "time stamp",
    },
    {"name": "effective_plimit", "width": 18, "aliases": None, "unit": "seconds"},
    {"name": "plimit_remain", "width": 15, "aliases": None, "unit": "seconds"},
    {"name": "effective_eplimit", "width": 19, "aliases": None, "unit": "seconds"},
    {"name": "eplimit_remain", "width": 16, "aliases": None, "unit": "seconds"},
    {"name": "cpu_used", "width": 10, "aliases": None, "unit": None},
    {"name": "run_time", "width": 15, "aliases": None, "unit": "seconds"},
    {"name": "idle_factor", "width": 11, "aliases": None, "unit": None},
    {"name": "exception_status", "width": 16, "aliases": "except_stat", "unit": None},
    {"name": "slots", "width": 5, "aliases": None, "unit": None},
    {"name": "mem", "width": 15, "aliases": None, "unit": "LSF_UNIT_FOR_LIMITS"},
    {"name": "max_mem", "width": 15, "aliases": None, "unit": "LSF_UNIT_FOR_LIMITS"},
    {"name": "avg_mem", "width": 15, "aliases": None, "unit": "LSF_UNIT_FOR_LIMITS"},
    {"name": "memlimit", "width": 15, "aliases": None, "unit": "LSF_UNIT_FOR_LIMITS"},
    {"name": "swap", "width": 15, "aliases": None, "unit": "LSF_UNIT_FOR_LIMITS"},
    {"name": "swaplimit", "width": 15, "aliases": None, "unit": "LSF_UNIT_FOR_LIMITS"},
    {"name": "gpu_num", "width": 10, "aliases": "gnum", "unit": None},
    {"name": "gpu_mode", "width": 20, "aliases": "gmode", "unit": None},
    {"name": "j_exclusive", "width": 15, "aliases": "j_excl", "unit": None},
    {"name": "gpu_alloc", "width": 30, "aliases": "galloc", "unit": None},
    {"name": "nthreads", "width": 10, "aliases": None, "unit": None},
    {"name": "hrusage", "width": 50, "aliases": None, "unit": None},
    {"name": "min_req_proc", "width": 12, "aliases": None, "unit": None},
    {"name": "max_req_proc", "width": 12, "aliases": None, "unit": None},
    {"name": "effective_resreq", "width": 17, "aliases": "eresreq", "unit": None},
    {"name": "combined_resreq", "width": 20, "aliases": "cresreq", "unit": None},
    {"name": "network_req", "width": 15, "aliases": None, "unit": None},
    {"name": "filelimit", "width": 10, "aliases": None, "unit": None},
    {"name": "corelimit", "width": 15, "aliases": None, "unit": None},
    {"name": "stacklimit", "width": 15, "aliases": None, "unit": None},
    {"name": "processlimit", "width": 12, "aliases": None, "unit": None},
    {"name": "runtimelimit", "width": 12, "aliases": None, "unit": None},
    {"name": "plimit", "width": 10, "aliases": None, "unit": "seconds"},
    {"name": "eplimit", "width": 10, "aliases": None, "unit": "seconds"},
    {"name": "input_file", "width": 10, "aliases": None, "unit": None},
    {"name": "output_file", "width": 11, "aliases": None, "unit": None},
    {"name": "error_file", "width": 10, "aliases": None, "unit": None},
    {"name": "output_dir", "width": 15, "aliases": None, "unit": None},
    {"name": "sub_cwd", "width": 10, "aliases": None, "unit": None},
    {"name": "exec_home", "width": 10, "aliases": None, "unit": None},
    {"name": "exec_cwd", "width": 10, "aliases": None, "unit": None},
    {"name": "licproject", "width": 20, "aliases": None, "unit": None},
    {"name": "forward_cluster", "width": 15, "aliases": "fwd_cluster", "unit": None},
    {"name": "forward_time", "width": 15, "aliases": "fwd_time", "unit": "time stamp"},
    {"name": "srcjobid", "width": 8, "aliases": None, "unit": None},
    {"name": "dstjobid", "width": 8, "aliases": None, "unit": None},
    {"name": "source_cluster", "width": 15, "aliases": "srcluster", "unit": None},
    {"name": "energy", "width": None, "aliases": None, "unit": "Joule"},
    {"name": "gpfsio", "width": None, "aliases": None, "unit": None},
]
